apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cp-kafka-connect
  namespace: kafka
  labels:
    app: cp-kafka-connect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-kafka-connect
      release: kafka
  template:
    metadata:
      labels:
        app: cp-kafka-connect
        release: kafka
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5556'
    spec:
      initContainers:
        - name: plugins-installer
          image: 'confluentinc/cp-kafka-connect:6.1.0'
          imagePullPolicy: 'IfNotPresent'
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/confluent-hub-components
          command:
            - confluent-hub
            - install
            - --no-prompt
            - confluentinc/kafka-connect-jdbc:10.2.4
      containers:
        - name: prometheus-jmx-exporter
          image: 'solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143'
          imagePullPolicy: 'IfNotPresent'
          command:
            - java
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+UseCGroupMemoryLimitForHeap
            - -XX:MaxRAMFraction=1
            - -XshowSettings:vm
            - -jar
            - jmx_prometheus_httpserver.jar
            - '5556'
            - /etc/jmx-kafka-connect/jmx-kafka-connect-prometheus.yml
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-kafka-connect
        - name: cp-kafka-connect-server
          image: 'confluentinc/cp-kafka-connect:6.1.0'
          imagePullPolicy: 'IfNotPresent'
          volumeMounts:
            - name: plugins
              mountPath: /usr/share/confluent-hub-components
          ports:
            - name: kafka-connect
              containerPort: 8083
              protocol: TCP
            - containerPort: 5555
              name: jmx
          env:
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-cp-kafka-headless:9092
            - name: CONNECT_GROUP_ID
              value: kafka
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: kafka-cp-kafka-connect-config
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: kafka-cp-kafka-connect-offset
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: kafka-cp-kafka-connect-status
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: http://kafka-cp-schema-registry:8081
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: http://kafka-cp-schema-registry:8081
            - name: KAFKA_HEAP_OPTS
              value: '-Xms512M -Xmx512M'
            - name: 'CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR'
              value: '1'
            - name: 'CONNECT_INTERNAL_KEY_CONVERTER'
              value: 'org.apache.kafka.connect.json.JsonConverter'
            - name: 'CONNECT_INTERNAL_VALUE_CONVERTER'
              value: 'org.apache.kafka.connect.json.JsonConverter'
            - name: 'CONNECT_KEY_CONVERTER'
              value: 'io.confluent.connect.avro.AvroConverter'
            - name: 'CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE'
              value: 'false'
            - name: 'CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR'
              value: '1'
            - name: 'CONNECT_PLUGIN_PATH'
              value: '/usr/share/java,/usr/share/confluent-hub-components'
            - name: 'CONNECT_STATUS_STORAGE_REPLICATION_FACTOR'
              value: '1'
            - name: 'CONNECT_VALUE_CONVERTER'
              value: 'io.confluent.connect.avro.AvroConverter'
            - name: 'CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE'
              value: 'false'
            - name: KAFKA_JMX_PORT
              value: '5555'
      volumes:
        - name: jmx-config
          configMap:
            name: kafka-cp-kafka-connect-jmx-configmap
        - name: plugins
          emptyDir: {}
