# repo:	https://confluentinc.github.io/cp-helm-charts 
# chart: cp-helm-charts 
# namespace: kafka 
# name: kafka 
cp-zookeeper:
  servers: 1
  persistence:
    enabled: false
    dataDirSize: 6Gi
    dataDirStorageClass: "ebs-sc"
    dataLogDirSize: 4Gi
    dataLogDirStorageClass: "ebs-sc"
  # heapOptions: "-Xms256M -Xmx256M"
  prometheus:
    jmx:
      enabled: false
cp-kafka:
  brokers: 1
  persistence:
    enabled: false
    size: 6Gi
    storageClass: ebs-sc
  # heapOptions: "-Xms256M -Xmx256M"
  configurationOverrides:
    "offsets.topic.replication.factor": 1
    "default.replication.factor": 1
    "confluent.metrics.reporter.topic.replicas": 1
  prometheus:
    jmx:
      enabled: false
cp-control-center:
  enabled: true
  configurationOverrides:
    "replication.factor": 1
    "default.replication.factor": 1
    "confluent.metrics.reporter.topic.replicas": 1
cp-schema-registry:
  enabled: true
cp-kafka-rest:
  enabled: false
cp-kafka-connect:
  enabled: false
cp-ksql-server:
  enabled: false


